import type { ReactNode } from "react";
import type { CardSummary, Mechanic } from "../../types";
import { type FilterState, type FilterStateUpdater, type MechanicSection, type ResultsViewMode } from "../shared/filterState";
type TableSortKey = "name" | "colors" | "manaValue" | "manaCost" | "typeLine" | "ownedCount" | "rawOwnedCount" | "set" | "rarity" | "mechanics";
type SearchScreenProps = {
    filtersCollapsed: boolean;
    onCollapseFilters: () => void;
    onExpandFilters: () => void;
    onOpenDeckDrawer: () => void;
    selectedDeckLabel: string;
    activeDeckTotalCards: number;
    searchState: FilterState;
    updateSearchFilters: FilterStateUpdater;
    selectedSearchMechanics: Mechanic[];
    sidebarFavorites: Mechanic[];
    sidebarDerivedGroups: MechanicSection[];
    sidebarMechanicSelection: string[];
    onToggleMechanic: (slug: string) => void;
    onOpenGlossary: () => void;
    cards: CardSummary[];
    cardsTotal: number;
    searchLoading: boolean;
    visibleResultsCount: number;
    onVisibleResultsCountChange: (updater: (current: number) => number) => void;
    viewMode: ResultsViewMode;
    onViewModeChange: (mode: ResultsViewMode) => void;
    visibleCards: CardSummary[];
    visibleSortedCards: CardSummary[];
    onClearDrilldown: () => void;
    onToggleTableSort: (key: TableSortKey) => void;
    onOpenCardDetail: (card: CardSummary) => void;
    renderActions: (card: CardSummary) => ReactNode;
};
export declare function SearchScreen({ filtersCollapsed, onCollapseFilters, onExpandFilters, onOpenDeckDrawer, selectedDeckLabel, activeDeckTotalCards, searchState, updateSearchFilters, selectedSearchMechanics, sidebarFavorites, sidebarDerivedGroups, sidebarMechanicSelection, onToggleMechanic, onOpenGlossary, cards, cardsTotal, searchLoading, visibleResultsCount, onVisibleResultsCountChange, viewMode, onViewModeChange, visibleCards, visibleSortedCards, onClearDrilldown, onToggleTableSort, onOpenCardDetail, renderActions }: SearchScreenProps): import("react/jsx-runtime").JSX.Element;
export {};
