import type { AppStatus, CollectionImportSummary, CollectorCaptureImportSummary, CollectorCaptureStatus, UntappedImportSummary, UntappedCaptureStatus } from "../../types";
type ImportScreenProps = {
    status: AppStatus | null;
    formatDateTime: (value: string | null) => string;
    formatFileSize: (size: number) => string;
    untappedCaptureSnippet: string;
    untappedHelperStatus: UntappedCaptureStatus | null;
    untappedGuideActive: boolean;
    untappedHelperLoading: boolean;
    untappedPreviewLoading: boolean;
    untappedPreview: UntappedImportSummary | null;
    untappedPreviewSource: "manual-file" | "latest-capture" | null;
    untappedImporting: boolean;
    untappedFile: File | null;
    onStartUntappedGuide: () => void;
    onCopyUntappedSnippet: () => void;
    onPreviewLatestUntappedCapture: () => void;
    onStopUntappedGuide: () => void;
    onUntappedPreview: (event: React.ChangeEvent<HTMLInputElement>) => void;
    onConfirmUntappedImport: () => void;
    collectorHelperStatus: CollectorCaptureStatus | null;
    collectorHelperLoading: boolean;
    collectorSnapshotPreviewLoading: boolean;
    collectorSnapshotImporting: boolean;
    collectorSnapshotPreview: CollectionImportSummary | CollectorCaptureImportSummary | null;
    collectorPreviewSource: "manual-file" | "latest-capture" | null;
    collectorSnapshotFile: File | null;
    onCaptureLatestCollectorSnapshot: () => void;
    onPreviewLatestCollectorSnapshot: () => void;
    onCollectorSnapshotPreview: (event: React.ChangeEvent<HTMLInputElement>) => void;
    onConfirmCollectorSnapshotImport: () => void;
    onImportCsv: (event: React.ChangeEvent<HTMLInputElement>) => void;
    formatImportPreviewContext: (preview: CollectionImportSummary) => string;
};
export declare function ImportScreen({ status, formatDateTime, formatFileSize, untappedCaptureSnippet, untappedHelperStatus, untappedGuideActive, untappedHelperLoading, untappedPreviewLoading, untappedPreview, untappedPreviewSource, untappedImporting, untappedFile, onStartUntappedGuide, onCopyUntappedSnippet, onPreviewLatestUntappedCapture, onStopUntappedGuide, onUntappedPreview, onConfirmUntappedImport, collectorHelperStatus, collectorHelperLoading, collectorSnapshotPreviewLoading, collectorSnapshotImporting, collectorSnapshotPreview, collectorPreviewSource, collectorSnapshotFile, onCaptureLatestCollectorSnapshot, onPreviewLatestCollectorSnapshot, onCollectorSnapshotPreview, onConfirmCollectorSnapshotImport, onImportCsv, formatImportPreviewContext }: ImportScreenProps): import("react/jsx-runtime").JSX.Element;
export {};
